apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clustercreators.alejandroesc.com
spec:
  group: alejandro.escobar.com
  version: v1alpha1
  scope: Namespaced
  names:
    plural: clustercreators
    singular: clustercreator
    kind: ClusterCreator
    shortnames:
      - cc
  subresources:
      status: {}
  openAPIV3Schema:
        properties:
          spec:
            properties:
              clusterName:
                type: String
