apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: sampleresources.alejandroesc.com
spec:
  group: alejandro.escobar.com
  version: v1alpha1
  scope: Namespaced
  names:
    plural: sampleresources
    singular: sampleresource
    kind: SampleResource
    shortnames:
      - cc
  subresources:
      status: {}
  openAPIV3Schema:
      properties:
        spec:
          properties:
            clusterName:
              type: String
