/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/alejandroEsc/k8s-provisioner-juju-example/pkg/apis/controller/v1alpha1"
	scheme "github.com/alejandroEsc/k8s-provisioner-juju-example/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterCreatorsGetter has a method to return a ClusterCreatorInterface.
// A group's client should implement this interface.
type ClusterCreatorsGetter interface {
	ClusterCreators(namespace string) ClusterCreatorInterface
}

// ClusterCreatorInterface has methods to work with ClusterCreator resources.
type ClusterCreatorInterface interface {
	Create(*v1alpha1.ClusterCreator) (*v1alpha1.ClusterCreator, error)
	Update(*v1alpha1.ClusterCreator) (*v1alpha1.ClusterCreator, error)
	UpdateStatus(*v1alpha1.ClusterCreator) (*v1alpha1.ClusterCreator, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.ClusterCreator, error)
	List(opts v1.ListOptions) (*v1alpha1.ClusterCreatorList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterCreator, err error)
	ClusterCreatorExpansion
}

// clusterCreators implements ClusterCreatorInterface
type clusterCreators struct {
	client rest.Interface
	ns     string
}

// newClusterCreators returns a ClusterCreators
func newClusterCreators(c *ControllerV1alpha1Client, namespace string) *clusterCreators {
	return &clusterCreators{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterCreator, and returns the corresponding clusterCreator object, and an error if there is any.
func (c *clusterCreators) Get(name string, options v1.GetOptions) (result *v1alpha1.ClusterCreator, err error) {
	result = &v1alpha1.ClusterCreator{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clustercreators").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterCreators that match those selectors.
func (c *clusterCreators) List(opts v1.ListOptions) (result *v1alpha1.ClusterCreatorList, err error) {
	result = &v1alpha1.ClusterCreatorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clustercreators").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterCreators.
func (c *clusterCreators) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clustercreators").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a clusterCreator and creates it.  Returns the server's representation of the clusterCreator, and an error, if there is any.
func (c *clusterCreators) Create(clusterCreator *v1alpha1.ClusterCreator) (result *v1alpha1.ClusterCreator, err error) {
	result = &v1alpha1.ClusterCreator{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clustercreators").
		Body(clusterCreator).
		Do().
		Into(result)
	return
}

// Update takes the representation of a clusterCreator and updates it. Returns the server's representation of the clusterCreator, and an error, if there is any.
func (c *clusterCreators) Update(clusterCreator *v1alpha1.ClusterCreator) (result *v1alpha1.ClusterCreator, err error) {
	result = &v1alpha1.ClusterCreator{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clustercreators").
		Name(clusterCreator.Name).
		Body(clusterCreator).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *clusterCreators) UpdateStatus(clusterCreator *v1alpha1.ClusterCreator) (result *v1alpha1.ClusterCreator, err error) {
	result = &v1alpha1.ClusterCreator{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clustercreators").
		Name(clusterCreator.Name).
		SubResource("status").
		Body(clusterCreator).
		Do().
		Into(result)
	return
}

// Delete takes name of the clusterCreator and deletes it. Returns an error if one occurs.
func (c *clusterCreators) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clustercreators").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterCreators) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clustercreators").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched clusterCreator.
func (c *clusterCreators) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.ClusterCreator, err error) {
	result = &v1alpha1.ClusterCreator{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clustercreators").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
